name: PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
  sonarqube-scan:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java (SonarQube CLI requires Java)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Step 3: Run SonarQube Scan
      # - name: Run SonarQube Scan
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Add this in your GitHub Secrets
      #   run: |
      #     curl -o sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856.zip
      #     unzip sonar-scanner.zip -d $HOME/
      #     export PATH=$HOME/sonar-scanner-4.8.0.2856-linux/bin:$PATH
      #     sonar-scanner \
      #       -Dsonar.projectKey=your-project-key \
      #       -Dsonar.sources=. \
      #       -Dsonar.host.url=https://your-sonarqube-server \
      #       -Dsonar.login=$SONAR_TOKEN

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run Unit Tests
      - name: Run Unit Tests
        run: |
          pytest